### PR TITLE
Type checking and descriptive errors

### PR DESCRIPTION
**Pull request by RyanMarcus**
I had some issues getting the package to work because I hadn't realized exactly what format the parameters needed to be passed as. I've added some type checking code to throw descriptive errors in case someone else has the same trouble.

### CODE REVIEW

**Comment by omphalos** [comment]
@RyanMarcus thanks for putting together this PR!

A few minor requests.  First would you mind adopting the existing code style (semicolon-free and two space indents).  Second I wonder if we could remove the lodash dependency?  This will decrease the size of the payload in the browser in case someone wants to use it there.  I only see two methods (`_.has` which can be replaced by the `in` operator or `hasOwnProperty` and _.isArray which can be replaced by `instanceof Array`).  Finally I wonder if you mind preserving the order of functions (I see that `push` is moved in the file) - I think this will clean up the diff.

Again I appreciate you taking the time to put this PR together.  I think it's a nice improvement will make the library more user-friendly.

**Comment by RyanMarcus** [comment]
I may lose a small bit of my sanity taking out the semicolons, but I will. And I can cut out the lodash dependency as well. I'll clean this up this weekend or Monday.

**Comment by omphalos** [comment]
> I may lose a small bit of my sanity taking out the semicolons

Haha, sorry.  Everyone has their own preferences.  I just want to keep the repo consistent.

**Comment by RyanMarcus** [comment]
I think those commits clean up most of the issues, including removing the lodash dep.

**Comment by omphalos** [comment]
@RyanMarcus thanks for making these changes.

A few minor remaining points:

I see tabs in some places (not spaces) - sorry I didn't notice this before.  These lines show up in the diff.

I'd like to preserve the existing two-space style for package.json as well, if you don't mind.

Finally I wonder if you wouldn't mind squashing these commits?  I think that would clean up the commit history, if that's alright with you.

**Comment by RyanMarcus** [comment]
I've been a Mercurial person for so long, I completely forgot that "history isn't sacred" over here in Git-land. :) I've rebased everything and force-pushed. The diffs look pretty spotless to me now.

Thanks,

Ryan

**Comment by RyanMarcus** [comment]
Oh -- while I don't think that any code I added will change the API for any reasonable user, it is possible that if someone was passing in an object that had an "x" or "y" property from farther up the prototype chain, it won't work anymore. Up to you, but you might want to bump to 0.10.0 or something.

**Comment by omphalos** [comment]
Thanks, @RyanMarcus! It looks great.  I'll bump the version per your suggestion as well.  I appreciate this work you've done!

**Pull request merged**
